sudo: required

language: cpp


compiler:
  - gcc

arch:
  packages:
    - carla
    - git
    - qt5-tools
    - python
    - cmake
  script:
    - "git clone https://github.com/progwolff/performer.git"
    - "cd performer/dist/arch/ && makepkg -i"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
