#!/bin/bash

if [ -f /usr/bin/python3 ]; then
  PYTHON=/usr/bin/python3
else
  PYTHON=python
fi

if [ "$1" = "--gdb" ]; then
  PYTHON="gdb --args $PYTHON"
fi

INSTALL_PREFIX="/usr"
export PATH="$INSTALL_PREFIX"/lib/carla:$PATH
exec $PYTHON "$INSTALL_PREFIX"/share/carla/performer-carla --with-appname="$0" --with-libprefix="$INSTALL_PREFIX" "$@"
